### ISSUE TITLE
Autosave lists to file

### ISSUE THREAD

**Issue by calhix** [harr1424/ListMaker#8]
Really love the app and simplicity of it. Would there be a way to autosave any changes (new lists and list items) to a file? This would then be great to use syncthing with to sync grocery lists between users.

**Comment by harr1424** [comment]
Thanks for your positive feedback, I learned a lot while creating the app. It is definitely possible to export and import database files using Room, I will get started on this feature this weekend and let you know when to expect an update in FDroid.

**Comment by harr1424** [comment]
I may have spoken too soon, I remembered seeing functionality to pre-populate a Room database, but exporting an existing database isn't directly supported by the Room library. There may be a workaround, however, I am posting the below links so that I can reference them later: 

[Google Issue Tracker](https://issuetracker.google.com/issues/154588984?pli=1)

[Related GitHub Issue](https://github.com/android/architecture-components-samples/issues/340)

**Comment by harr1424** [comment]
Thanks again for this feature request, but I have not been able to find a reliable or supported way to implement this. It looks like at least one person has requested Google implement this ability into a future version of the Room library, but they have stated they have no plans to do so.
